# Generated by Django 4.0 on 2022-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationclass',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=150)),
                ('slot_type', models.CharField(choices=[('TWO', 'TWO WHEELER'), ('FOUR', 'FOUR WHEELER')], max_length=150)),
                ('image', models.ImageField(upload_to='media/parking')),
                ('slot_status', models.CharField(choices=[('F', 'FULL'), ('A', 'AVAILABLE')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
